"use client"
import React, { Suspense, lazy, useEffect, useState } from 'react';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import './globals.css';
import Navbar from '@/components/Navbar';
import { ThemeProvider } from '@/contexts/ThemeContext';
// استخدام React.lazy لتحميل مكون Footer بشكل كسول
const LazyFooter = lazy(() => import('@/components/Footer'));
const inter = Inter({ subsets: ['latin'] });

const RootLayout = ({ children }) => {
  const [isClient, setIsClient] = useState(false);

useEffect(() => {
  // تحديث الحالة بعد ترطيب الصفحة على العميل
  setIsClient(true);
}, []);
  return(
    <html>
    <ThemeProvider>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* Any other head elements here */}
      </Head>
      <body className={inter.className}>
        <Navbar type="dark" />
        {children}
      </body>
      {isClient && (
        <Suspense fallback={<div>Loading Footer...</div>}>
          <LazyFooter />
        </Suspense>
      )}
    </ThemeProvider>
  </html>
  )
} 

export default RootLayout;
