"use client"
import { Inter } from 'next/font/google';
import Head from 'next/head';
import './globals.css';
import Navbar from '@/components/Navbar';
import { ThemeProvider } from '@/contexts/ThemeContext';
import Footer from '@/components/Footer';
const inter = Inter({ subsets: ['latin'] });

const RootLayout = ({ children }) => (
  <html>
  <ThemeProvider>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      {/* Any other head elements here */}
    </Head>
    <body className={inter.className}>
      <Navbar type="dark" />
      {children}
    </body>
    <Footer/>
  </ThemeProvider>
  </html>
);

export default RootLayout;
