'use client';

import React, { Suspense, lazy, useEffect, useState } from 'react';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import './globals.css';
import { ThemeProvider } from '@/contexts/ThemeContext';

// Use React.lazy for lazy loading the Footer component
const LazyNavbar = lazy(() => import('@/components/Navbar'));
const LazyFooter = lazy(() => import('@/components/Footer'));
const inter = Inter({ subsets: ['latin'] });

const RootLayout = ({ children }) => {
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
  }, []);

  return ( // Added a space after "return"
    <html lang="en"> {/* Added the lang attribute */}
      <ThemeProvider>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          {/* Any other head elements here */}
        </Head>
        <body className={inter.className}>
          {isClient && (
            <Suspense fallback={<div>Loading Navbar...</div>}>
              <LazyNavbar type="dark" />
            </Suspense>
          )}
          {children}
        </body>
        {isClient && (
          <Suspense fallback={<div>Loading Footer...</div>}>
            <LazyFooter />
          </Suspense>
        )}
      </ThemeProvider>
    </html>
  )
} 

export default RootLayout;
